import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { hashPassword, generateTempPassword } from "@/lib/auth/password";
import { sendTempPasswordEmail } from "@/lib/mailer";
import { z } from "zod";

// See src/app/api/health/route.ts for why this matters.
export const dynamic = "force-dynamic";

// Admin-only account management. Everyone shares the same garage data — this
// is just per-person login identity, not per-user data isolation.

const createUserSchema = z.object({
  username: z.string().min(3).max(50).regex(/^[a-zA-Z0-9_.-]+$/, "Letters, numbers, _ . - only"),
  // Omit password to auto-generate a temp one and email it (requires email).
  password: z.string().min(8).max(200).optional(),
  email: z.string().email().optional(),
  role: z.enum(["admin", "member"]).default("member"),
}).refine(data => data.password || data.email, {
  message: "Provide a password, or an email to send an auto-generated one to",
});

function requireAdmin(req: NextRequest): NextResponse | null {
  if (req.headers.get("x-user-role") !== "admin") {
    return NextResponse.json({ error: "Admin access required" }, { status: 403 });
  }
  return null;
}

export async function GET(req: NextRequest) {
  const denied = requireAdmin(req);
  if (denied) return denied;

  try {
    const users = await prisma.user.findMany({
      select: { id: true, username: true, email: true, role: true, mustChangePassword: true, createdAt: true },
      orderBy: { createdAt: "asc" },
    });
    return NextResponse.json(users);
  } catch {
    return NextResponse.json({ error: "Failed to fetch users" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  const denied = requireAdmin(req);
  if (denied) return denied;

  try {
    const body = await req.json();
    const data = createUserSchema.parse(body);

    const existing = await prisma.user.findUnique({ where: { username: data.username } });
    if (existing) {
      return NextResponse.json({ error: "That username is already taken" }, { status: 409 });
    }

    // No password given → auto-generate one and email it (mustChangePassword
    // forces them to set their own on first sign-in). A manually-typed
    // password (the pre-existing flow) is used as-is, no forced change.
    const autoGenerated = !data.password;
    const plainPassword = data.password ?? generateTempPassword();

    const user = await prisma.user.create({
      data: {
        username: data.username,
        email: data.email,
        role: data.role,
        passwordHash: hashPassword(plainPassword),
        mustChangePassword: autoGenerated,
      },
      select: { id: true, username: true, email: true, role: true, mustChangePassword: true, createdAt: true },
    });

    if (autoGenerated && data.email) {
      const result = await sendTempPasswordEmail(data.email, user.username, plainPassword, req.nextUrl.origin);
      if (!result.ok) {
        // Account still exists — surface the password so the admin can hand
        // it over manually instead of the new user being locked out.
        return NextResponse.json({ ...user, tempPassword: plainPassword, emailError: result.error }, { status: 201 });
      }
    }
    return NextResponse.json(user, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.errors[0]?.message || error.errors }, { status: 400 });
    }
    const msg = error instanceof Error ? error.message : String(error);
    console.error("[POST /api/admin/users]", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
